spring:
    application:
        name : movie-info-service
#    we won't use cloud config for now
#    cloud:
#        config:
#            uri: http://localhost:8888

server:
    port : 8082

api:
    key: cea3b7a0b210db1ea9f3707365849dd8


eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://192.168.207.142:8761/eureka
