spring:
    application:
        name : movie-rating-service
#    we won't use cloud config for now
#    cloud:
#        config:
#            uri: http://localhost:8888

server:
    port : 8083

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://192.168.207.142:8761/eureka
