spring:
    application:
        name : movie-catalog-service
    cloud:
        config:
            uri: http://localhost:8888

server:
    port : 8081

my:
    greetings : Hello from properties
    list:
        value : one,two,three


db:
    connection : "{connection: 'http', username: 'abc', password: 'pwd'}"
    host : 127.0.0.1
    port : 3333




